import { z } from "zod";

export const alunoSchema = z.object({
  rm: z.string(),
  ra: z.string().length(13),
  nis: z.string(),
  "aluno-nome": z.string(),
  "aluno-nascimento": z.string(),
  "opcao-cpf": z.string(),
  "opcao-rg": z.string(),
  "aluno-rg-cpf": z.string(),
  "opcao-fem": z.string(),
  "opcao-masc": z.string(),
  "raca-branca": z.string(),
  "raca-preta": z.string(),
  "raca-parda": z.string(),
  "raca-amarela": z.string(),
  "raca-indigina": z.string(),
  "raca-nao-declarada": z.string(),
  nacionalidade: z.string(),
  "etado-civil": z.string(),
  "munucupio-nascimento": z.string(),
  "estado-nascimento": z.string(),
  "comarca-nascimento": z.string(),
  "uf-nascimento": z.string(),
  "certidao-distrito": z.string(),
  "certidao-folha": z.string(),
  "certidao-livro": z.string(),
  "certidao-numero": z.string(),
  "certidao-nova": z.string(),
  "pai-nome": z.string(),
  "pai-data-nascimento": z.string(),
  "pai-rg": z.string(),
  "pai-cpf": z.string(),
  "pai-telefone": z.string(),
  "pai-email": z.string(),
  "mae-nome": z.string(),
  "mae-data-nascimento": z.string(),
  "mae-rg": z.string(),
  "mae-cpf": z.string(),
  "mae-telefone": z.string(),
  "mae-email": z.string(),
  "endereco-rua": z.string(),
  "endereco-numero": z.string(),
  "endereco-bairro": z.string(),
  "endereco-cidade": z.string(),
  "endereco-cep": z.string(),
  "endereco-tel": z.string(),
  "endereco-cel": z.string(),
  "outras-informacoes": z.string(),
  "matricula-serie": z.string(),
  "matricula-ensino": z.string(),
  "matricula-dia": z.string(),
  "matricula-mes": z.string(),
  "matricula-ano": z.string(),
});

// Tipagem gerada a partir do schema
export type AlunoInfo = z.infer<typeof alunoSchema>;


